# Generated by Django 5.2.16 on 2026-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_unique_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_google_login',
            field=models.DateTimeField(blank=True, help_text='Cuándo entró por última vez con su cuenta de Google.', null=True, verbose_name='Última entrada con Google'),
        ),
    ]
