# Generated by Django 5.2.16 on 2026-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_google_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('driver', 'Conductor'), ('hse', 'HSE')], max_length=20),
        ),
    ]
