# Generated by Django 5.2.16 on 2026-09-23 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_hse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clave de sesión')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de sesión')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión abierta',
                'verbose_name_plural': 'sesiones abiertas',
            },
        ),
    ]
