# Generated by Django 5.2.16 on 2026-07-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'unidad de negocio',
                'verbose_name_plural': 'unidades de negocio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('creation', 'Alta'), ('activation', 'Activación'), ('deactivation', 'Desactivación'), ('invoice', 'Factura'), ('immobilization', 'Inmovilización'), ('reactivation', 'Reactivación'), ('insurance_renewal', 'Renovación de seguro'), ('penalty', 'Sanción'), ('location_change', 'Cambio de ubicación'), ('project_change', 'Cambio de proyecto'), ('breakdown', 'Avería'), ('km_reading', 'Lectura de km'), ('contract_change', 'Cambio de contrato'), ('fee_change', 'Cambio de cuota'), ('ceco_change', 'Cambio de CECO'), ('itv', 'ITV'), ('maintenance', 'Mantenimiento'), ('driver_change', 'Cambio de conductor')], max_length=30, verbose_name='Tipo de evento')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=60, verbose_name='Código')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe')),
                ('file', models.CharField(blank=True, help_text='Ruta o URL al PDF de la factura.', max_length=500, verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Pep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'PEP / CECO',
                'verbose_name_plural': 'PEP / CECO',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Nombre del proyecto')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'renting',
                'verbose_name_plural': 'rentings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventFeeChange',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fee_change', serialize=False, to='fleet.event')),
                ('old_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cuota anterior')),
                ('new_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cuota nueva')),
            ],
            options={
                'verbose_name': 'cambio de cuota',
                'verbose_name_plural': 'cambios de cuota',
            },
        ),
        migrations.CreateModel(
            name='EventItv',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='itv', serialize=False, to='fleet.event')),
                ('result', models.CharField(blank=True, help_text="p. ej. 'done' / 'not done'.", max_length=50, verbose_name='Resultado')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='Próxima ITV')),
            ],
            options={
                'verbose_name': 'ITV',
                'verbose_name_plural': 'ITVs',
            },
        ),
        migrations.CreateModel(
            name='EventLocationChange',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location_change', serialize=False, to='fleet.event')),
                ('old_location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación anterior')),
                ('new_location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación nueva')),
            ],
            options={
                'verbose_name': 'cambio de ubicación',
                'verbose_name_plural': 'cambios de ubicación',
            },
        ),
        migrations.CreateModel(
            name='EventPenalty',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='penalty', serialize=False, to='fleet.event')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
            ],
            options={
                'verbose_name': 'sanción',
                'verbose_name_plural': 'sanciones',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('proyecto', 'Proyecto'), ('pep', 'PEP / CECO')], max_length=20, verbose_name='Destino')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% imputado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fleet.invoice')),
                ('cost_center', models.ForeignKey(blank=True, help_text="Si el destino es 'PEP / CECO'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='fleet.pep', verbose_name='PEP / CECO')),
                ('project', models.ForeignKey(blank=True, help_text="Si el destino es 'Proyecto'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='fleet.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'imputación de factura',
                'verbose_name_plural': 'imputaciones de factura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=15, unique=True, verbose_name='Matrícula')),
                ('state', models.CharField(blank=True, choices=[('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('non_active', 'No activo'), ('itv', 'En ITV'), ('broken', 'Averiado'), ('accidente', 'Accidentado')], max_length=20, verbose_name='Estado')),
                ('is_substitute', models.BooleanField(default=False, verbose_name='¿Es vehículo de sustitución?')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('fuel', models.CharField(blank=True, choices=[('CNG', 'GNC'), ('Gasoline_E5', 'Gasolina E5'), ('Gasoline_E10', 'Gasolina E10'), ('Gasoline_E85', 'Gasolina E85'), ('Gasoline_E100', 'Gasolina E100'), ('Diesel_B', 'Diésel B'), ('Diesel_B7', 'Diésel B7'), ('Diesel_B10', 'Diésel B10'), ('Diesel_B20', 'Diésel B20'), ('Diesel_B30', 'Diésel B30'), ('B100', 'B100'), ('LPG', 'LPG'), ('Fueloleo', 'Fuelóleo'), ('Queroseno', 'Queroseno'), ('Gasolina_aviacion', 'Gasolina de aviación'), ('GLP', 'GLP'), ('Adblue', 'AdBlue'), ('Biometanol', 'Biometanol'), ('Gasoleo_marino', 'Gasóleo marino'), ('Biogas', 'Biogás'), ('Nafta', 'Nafta'), ('Biopropano', 'Biopropano'), ('Vehiculo_electrico_bateria', 'Eléctrico (batería)'), ('Vehiculo_hibrido_enchufable', 'Híbrido enchufable'), ('Queroseno_aviacion_renovable', 'Queroseno de aviación renovable'), ('Biometano', 'Biometano')], max_length=40, verbose_name='Combustible')),
                ('type', models.CharField(blank=True, choices=[('turismo', 'Turismo'), ('furgoneta', 'Furgoneta'), ('camion', 'Camión'), ('motocicleta', 'Motocicleta')], max_length=20, verbose_name='Tipo')),
                ('size', models.CharField(blank=True, choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20, verbose_name='Tamaño')),
                ('market_segment', models.CharField(blank=True, choices=[('mini', 'Mini'), ('supermini', 'Supermini'), ('mediano_inferior', 'Mediano inferior'), ('mediano_superior', 'Mediano superior'), ('ejecutivo', 'Ejecutivo'), ('lujo', 'Lujo'), ('deportivo', 'Deportivo'), ('4x4_dual', '4x4 / Dual'), ('MPV', 'MPV')], max_length=30, verbose_name='Segmento de mercado')),
                ('veh_use', models.CharField(blank=True, choices=[('pasajeros', 'Pasajeros'), ('mercancia', 'Mercancía')], max_length=20, verbose_name='Uso (pasajeros/mercancía)')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Versión')),
                ('consumption', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo')),
                ('km_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km inicial')),
                ('km_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km final')),
                ('property', models.CharField(blank=True, choices=[('propio', 'Propio'), ('renting', 'Renting')], max_length=20, verbose_name='Propiedad')),
                ('business_use', models.CharField(blank=True, choices=[('on_project', 'Proyecto'), ('personal', 'Personal'), ('works', 'Obras')], max_length=20, verbose_name='Uso empresarial')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.businessunit', verbose_name='Unidad de negocio')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.country', verbose_name='País')),
                ('project', models.ForeignKey(blank=True, help_text="Obligatorio si el uso empresarial es 'Proyecto'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.project', verbose_name='Proyecto')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Opcional: responsable del vehículo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='KmReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('km_reading', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilómetros')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='km_readings', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'lectura de km',
                'verbose_name_plural': 'lecturas de km',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='event',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=60, verbose_name='Nº de contrato')),
                ('contract_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (meses)')),
                ('contract_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km contratados')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Cliente')),
                ('cif', models.CharField(blank=True, max_length=20, verbose_name='CIF')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('planned_end_date', models.DateField(verbose_name='Fin previsto')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin real')),
                ('month_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cuota mensual')),
                ('renting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='fleet.renting', verbose_name='Renting')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, help_text='NULL = en curso.', null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('propuesta', 'Propuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='propuesta', max_length=20, verbose_name='Estado')),
                ('usage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('averia', 'Avería'), ('mantenimiento', 'Mantenimiento'), ('itv', 'ITV'), ('accidente', 'Accidente')], max_length=20, verbose_name='Motivo')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, help_text='NULL = vínculo activo.', null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('main_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_links', to='fleet.vehicle', verbose_name='Vehículo principal')),
                ('substitute_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_links', to='fleet.vehicle', verbose_name='Vehículo de sustitución')),
            ],
            options={
                'verbose_name': 'vínculo de sustitución',
                'verbose_name_plural': 'vínculos de sustitución',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de uso')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_usages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'reparto de uso',
                'verbose_name_plural': 'repartos de uso',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventDriverChange',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_change', serialize=False, to='fleet.event')),
                ('new_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('old_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de conductor',
                'verbose_name_plural': 'cambios de conductor',
            },
        ),
        migrations.CreateModel(
            name='EventPepChange',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pep_change', serialize=False, to='fleet.event')),
                ('new_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.pep')),
                ('old_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.pep')),
            ],
            options={
                'verbose_name': 'cambio de PEP/CECO',
                'verbose_name_plural': 'cambios de PEP/CECO',
            },
        ),
        migrations.CreateModel(
            name='EventProjectChange',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project_change', serialize=False, to='fleet.event')),
                ('new_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.project')),
                ('old_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.project')),
            ],
            options={
                'verbose_name': 'cambio de proyecto',
                'verbose_name_plural': 'cambios de proyecto',
            },
        ),
    ]
