# Generated by Django 5.2.16 on 2026-07-21 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('type', models.CharField(choices=[('averia', 'Avería'), ('mantenimiento', 'Mantenimiento'), ('accidente', 'Accidente'), ('itv', 'ITV')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coste')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'incidencia',
                'verbose_name_plural': 'incidencias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('type', models.CharField(choices=[('permiso_circulacion', 'Permiso de circulación'), ('ficha_tecnica', 'Ficha técnica'), ('seguro', 'Seguro'), ('contrato', 'Contrato'), ('acta_entrega', 'Acta de entrega'), ('acta_devolucion', 'Acta de devolución'), ('parte_accidente', 'Parte de accidente'), ('fotos_danos', 'Fotos de daños'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('drive_url', models.CharField(blank=True, help_text='Ruta o URL al documento archivado.', max_length=500, verbose_name='URL en Drive')),
                ('expiry_date', models.DateField(blank=True, help_text='Para seguro, permiso, ITV…', null=True, verbose_name='Fecha de caducidad')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('caducado', 'Caducado'), ('pendiente_archivar', 'Pendiente de archivar')], default='vigente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('replaces', models.ForeignKey(blank=True, help_text='Versión anterior a la que reemplaza este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='fleet.document', verbose_name='Sustituye a')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='fleet.incident', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
