# Generated by Django 5.2.16 on 2026-07-21 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_incident_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='next_itv_date',
            field=models.DateField(blank=True, db_index=True, help_text='Denormalizado del último `EventItv.next_due`; lo refresca el job `refresh_next_itv` y alimenta la alerta de ITV escalonada (HU-5.1).', null=True, verbose_name='Próxima ITV'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('type', models.CharField(choices=[('itv_due', 'ITV próxima / vencida'), ('km_reading_pending', 'Lectura de km pendiente'), ('km_overage', 'Exceso de km proyectado'), ('no_driver', 'Vehículo sin conductor')], max_length=30, verbose_name='Tipo')),
                ('level', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Aviso'), ('critical', 'Crítica')], default='info', max_length=10, verbose_name='Nivel')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='open', max_length=15, verbose_name='Estado')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Mensaje')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('dedup_key', models.CharField(help_text='Identidad estable de la alerta; evita duplicados entre ejecuciones.', max_length=120, unique=True, verbose_name='Clave de deduplicación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('user', models.ForeignKey(blank=True, help_text='Destinatario/sujeto de la alerta (p. ej. el conductor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fleet.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='fleet_alert_type_604bb7_idx'), models.Index(fields=['vehicle', 'status'], name='fleet_alert_vehicle_9522cb_idx')],
            },
        ),
    ]
