# Generated by Django 5.2.16 on 2026-07-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_next_itv_date_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drive_folder_url',
            field=models.URLField(blank=True, help_text='Carpeta del vehículo en el repositorio documental (HU-4.2). La crea el archivador la primera vez que se archiva un documento.', verbose_name='Carpeta de Drive'),
        ),
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('requested_type', models.CharField(blank=True, choices=[('turismo', 'Turismo'), ('furgoneta', 'Furgoneta'), ('camion', 'Camión'), ('motocicleta', 'Motocicleta')], max_length=20, verbose_name='Tipo solicitado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('jira_key', models.CharField(blank=True, help_text='Issue de Jira de la solicitud (aprobación externa).', max_length=40, verbose_name='Clave de Jira')),
                ('status', models.CharField(choices=[('approved', 'Aprobada'), ('assigned', 'Vehículo asignado'), ('rejected', 'Rechazada'), ('closed', 'Cerrada')], default='approved', max_length=15, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='fleet.vehicle', verbose_name='Vehículo asignado')),
            ],
            options={
                'verbose_name': 'solicitud de vehículo',
                'verbose_name_plural': 'solicitudes de vehículo',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('jira_key', ''), _negated=True), fields=('jira_key',), name='unique_jira_key')],
            },
        ),
    ]
