# Generated by Django 5.2.16 on 2026-07-21 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_drive_folder_url_vehiclerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['vehicle', 'end_date', 'status'], name='fleet_assig_vehicle_38115c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['driver', 'end_date'], name='fleet_assig_driver__66df21_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vehicle', 'status'], name='fleet_docum_vehicle_2926a9_idx'),
        ),
        migrations.AddIndex(
            model_name='kmreading',
            index=models.Index(fields=['vehicle', 'reading_date'], name='fleet_kmrea_vehicle_df1bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['state'], name='fleet_vehic_state_1a38e0_idx'),
        ),
    ]
