# Generated by Django 5.2.16 on 2026-07-22 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_rename_enum_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_active_assignment_per_vehicle',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('proposed', 'Propuesta'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('finished', 'Finalizada')], default='proposed', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('valid', 'Vigente'), ('expired', 'Caducado'), ('pending_archive', 'Pendiente de archivar')], default='valid', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('registration_certificate', 'Permiso de circulación'), ('technical_datasheet', 'Ficha técnica'), ('insurance', 'Seguro'), ('contract', 'Contrato'), ('delivery_report', 'Acta de entrega'), ('return_report', 'Acta de devolución'), ('accident_report', 'Parte de accidente'), ('damage_photos', 'Fotos de daños'), ('other', 'Otro')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('on_going', 'En curso'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('breakdown', 'Avería'), ('maintenance', 'Mantenimiento'), ('inspection', 'ITV'), ('accident', 'Accidente')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasolina'), ('diesel', 'Diésel'), ('LPG', 'GLP'), ('hybrid', 'Híbrido'), ('other', 'Otro')], max_length=40, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='market_segment',
            field=models.CharField(blank=True, choices=[('mini', 'Mini'), ('supermini', 'Supermini'), ('med_low', 'Mediano inferior'), ('med_sup', 'Mediano superior'), ('executive', 'Ejecutivo'), ('luxury', 'Lujo'), ('sports', 'Deportivo'), ('suv', '4x4 / Dual (SUV)'), ('MPV', 'MPV')], max_length=30, verbose_name='Segmento de mercado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('big', 'Grande')], max_length=20, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('itv', 'En ITV'), ('broken', 'Averiado'), ('retired', 'Baja'), ('non_active', 'No activo'), ('accidente', 'Accidentado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, choices=[('car', 'Turismo'), ('van', 'Furgoneta'), ('truck', 'Camión'), ('motorcycle', 'Motocicleta')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='veh_use',
            field=models.CharField(blank=True, choices=[('passengers', 'Pasajeros'), ('freight', 'Mercancía')], max_length=20, verbose_name='Uso (pasajeros/mercancía)'),
        ),
        migrations.AlterField(
            model_name='vehiclelink',
            name='reason',
            field=models.CharField(choices=[('breakdown', 'Avería'), ('maintenance', 'Mantenimiento'), ('inspection', 'ITV'), ('accident', 'Accidente')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='requested_type',
            field=models.CharField(blank=True, choices=[('car', 'Turismo'), ('van', 'Furgoneta'), ('truck', 'Camión'), ('motorcycle', 'Motocicleta')], max_length=20, verbose_name='Tipo solicitado'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('status', 'accepted')), fields=('vehicle',), name='unique_active_assignment_per_vehicle'),
        ),
    ]
