# Generated by Django 5.2.16 on 2026-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_remove_assignment_unique_active_assignment_per_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='penalty_per_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='€ por km de exceso sobre los contratados; alimenta la penalización estimada de la proyección (HU-3.4).', max_digits=6, null=True, verbose_name='Penalización por km (€)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Binario subido desde la app (cámara/galería del móvil, HU-4.1). Convive con `drive_url`: al archivarse en Drive se rellena la URL.', null=True, upload_to='documents/%Y/%m/', verbose_name='Fichero'),
        ),
    ]
