# Generated by Django 5.2.16 on 2026-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_contract_penalty_per_km_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('approved', 'Aprobada'), ('assigned', 'Vehículo asignado'), ('rejected', 'Rechazada'), ('closed', 'Cerrada')], default='approved', max_length=15, verbose_name='Estado'),
        ),
    ]
