# Generated by Django 5.2.16 on 2026-07-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_vehiclerequest_status'),
    ]

    operations = [
        # `invoice.file` guardaba "ruta o URL al PDF": se RENOMBRA (no se borra)
        # a `drive_url` para conservar lo ya registrado (Fase A3).
        migrations.RenameField(
            model_name='invoice',
            old_name='file',
            new_name='drive_url',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='drive_url',
            field=models.CharField(blank=True, help_text='Enlace al PDF de la factura.', max_length=500, verbose_name='URL en Drive'),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='ID del fichero en Google Drive (Fase A3). Lo rellena el Picker (vía escritorio) o el archivador al subir el multipart (vía móvil).', max_length=100, verbose_name='ID en Drive'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='ID del fichero en Google Drive (lo rellena el Picker al adjuntar).', max_length=100, verbose_name='ID en Drive'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='ID de la carpeta del vehículo en Google Drive (Fase A3): lo usa el archivador para subir y el Picker para listar (`folder-files`).', max_length=100, verbose_name='ID de carpeta en Drive'),
        ),
    ]
