# Generated by Django 5.2.16 on 2026-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_project_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='N2: editable en ficha y sincronizado al subir un documento de seguro con caducidad más reciente; alimenta la alerta de seguro (30/15/7).', null=True, verbose_name='Vencimiento del seguro'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unlimited_km',
            field=models.BooleanField(default=False, help_text='N3: sin proyección de km ni alertas de exceso; el contrato puede no llevar km contratados.', verbose_name='Km ilimitados'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('itv_due', 'ITV próxima / vencida'), ('insurance_due', 'Seguro próximo / vencido'), ('km_reading_pending', 'Lectura de km pendiente'), ('km_overage', 'Exceso de km proyectado'), ('no_driver', 'Vehículo sin conductor')], max_length=30, verbose_name='Tipo'),
        ),
    ]
