# Generated by Django 5.2.16 on 2026-07-30 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_populate_brand_model_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='brand',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='brand',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='company',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='company',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='company',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='country',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='country',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='country',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='document',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='document',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='document',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='incident',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='incident',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='invoiceallocation',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='invoiceallocation',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='invoiceallocation',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='invoiceallocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='kmreading',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='kmreading',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='kmreading',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='kmreading',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pep',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='pep',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='pep',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='pep',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='project',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='project',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='project',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='renting',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='renting',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='renting',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='renting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
