# Generated by Django 5.2.16 on 2026-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_brand_deactivated_at_brand_deactivated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmreading',
            name='estimated',
            field=models.BooleanField(default=False, help_text="N8b: creada por 'completar km faltantes' (media de N meses), no registrada por una persona. Trazabilidad del dato.", verbose_name='Estimada'),
        ),
    ]
