# Generated by Django 5.2.16 on 2026-07-30 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_kmreading_estimated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='renting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('template_key', models.CharField(blank=True, max_length=30, verbose_name='Plantilla')),
                ('recipient', models.CharField(blank=True, max_length=254, verbose_name='Destinatario')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido (sin destinatario / deshabilitado)')], max_length=10, verbose_name='Estado')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='fleet.alert', verbose_name='Alerta')),
            ],
            options={
                'verbose_name': 'envío de correo',
                'verbose_name_plural': 'envíos de correo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('body_html', models.TextField(blank=True, verbose_name='Firma (HTML)')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
            ],
            options={
                'verbose_name': 'firma de correo',
                'verbose_name_plural': 'firmas de correo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('key', models.CharField(choices=[('insurance_due', 'Seguro próximo / vencido (a la empresa de renting)'), ('km_overage', 'Exceso de km proyectado (al conductor)'), ('km_reading_pending', 'Lectura de km pendiente (al conductor)'), ('generic', 'Genérica (resto de avisos)')], max_length=30, unique=True, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('body_html', models.TextField(help_text='HTML saneado en servidor; variables {{matricula}}, {{conductor}}…', verbose_name='Cuerpo (HTML)')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='fleet.emailsignature', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'plantilla de correo',
                'verbose_name_plural': 'plantillas de correo',
                'ordering': ['key'],
            },
        ),
    ]
