# Generated by Django 5.2.16 on 2026-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_renting_contact_name_renting_email_emaillog_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['vehicle', 'event_date'], name='fleet_event_vehicle_88a261_idx'),
        ),
    ]
