# Generated by Django 5.2.16 on 2026-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_event_fleet_event_vehicle_88a261_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('insurance_due', 'Seguro próximo / vencido (a la empresa de renting)'), ('itv_due', 'ITV próxima / vencida (aviso de ITV)'), ('state_notice', 'Comunicado de estado del vehículo'), ('km_overage', 'Exceso de km proyectado (al conductor)'), ('km_reading_pending', 'Lectura de km pendiente (al conductor)'), ('generic', 'Genérica (resto de avisos)')], max_length=30, unique=True, verbose_name='Tipo'),
        ),
    ]
