# Generated by Django 5.2.16 on 2026-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_emailtemplate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='drive_url',
            field=models.CharField(blank=True, help_text='Enlace a la carpeta o el fichero del contrato en Google Drive.', max_length=500, verbose_name='Enlace en Drive'),
        ),
    ]
