# Generated by Django 5.2.16 on 2026-08-20 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_itv_result_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_active_assignment_per_vehicle',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclelink',
            name='unique_active_substitute_per_main',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclerequest',
            name='unique_jira_key',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='vehiclelink',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='vehiclelink',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='vehiclelink',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='vehiclelink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_active', True), ('status', 'accepted')), fields=('vehicle',), name='unique_active_assignment_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelink',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_active', True)), fields=('main_vehicle',), name='unique_active_substitute_per_main'),
        ),
        migrations.AddConstraint(
            model_name='vehiclerequest',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('jira_key', ''), _negated=True), ('is_active', True)), fields=('jira_key',), name='unique_jira_key'),
        ),
    ]
