# Generated by Django 5.2.16 on 2026-08-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_n7_deactivatable_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('template_key', models.CharField(blank=True, max_length=30, verbose_name='Plantilla')),
                ('recipient', models.CharField(max_length=254, verbose_name='Destinatario')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('body_html', models.TextField(verbose_name='Cuerpo (HTML)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido (sin más reintentos)')], default='pending', max_length=10, verbose_name='Estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('last_error', models.TextField(blank=True, verbose_name='Último error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_emails', to='fleet.alert', verbose_name='Alerta')),
            ],
            options={
                'verbose_name': 'correo en cola',
                'verbose_name_plural': 'correos en cola',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_outbox_status')],
            },
        ),
    ]
