# Generated by Django 5.2.16 on 2026-08-20 13:33

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_email_outbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclemodel',
            name='uniq_model_per_brand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_brand_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_business_unit_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uniq_company_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_country_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='pep',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_pep_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('project_name'), name='uniq_project_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='renting',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_renting_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(models.F('brand'), django.db.models.functions.text.Lower('name'), name='uniq_model_per_brand_ci'),
        ),
    ]
