# Generated by Django 5.2.16 on 2026-08-21 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_alert_drop_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('content', models.CharField(choices=[('summary', 'Resumen de la flota'), ('fleet', 'Informe de flota'), ('alerts', 'Informe de alertas'), ('costs', 'Informe de costes')], max_length=10, verbose_name='Contenido')),
                ('fmt', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV')], default='xlsx', help_text='Solo se aplica a los informes; el resumen va en el cuerpo del correo.', max_length=5, verbose_name='Formato')),
                ('frequency', models.CharField(choices=[('daily', 'Cada día'), ('weekly', 'Cada semana'), ('monthly', 'Cada mes')], max_length=10, verbose_name='Frecuencia')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día de la semana')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día del mes')),
                ('send_at', models.TimeField(help_text='Hora local. El despachador corre por tandas, así que puede salir algo después.', verbose_name='Hora')),
                ('enabled', models.BooleanField(default=True, help_text='Desactívalo para dejar de recibirlo sin perder la configuración.', verbose_name='Activo')),
                ('send_email', models.BooleanField(default=True, verbose_name='Enviar por correo')),
                ('extra_recipients', models.CharField(blank=True, help_text='Direcciones separadas por comas, además de la del usuario.', max_length=500, verbose_name='Otros destinatarios')),
                ('save_to_drive', models.BooleanField(default=False, verbose_name='Guardar en Google Drive')),
                ('drive_folder', models.CharField(blank=True, help_text='Id o URL de la carpeta donde se deja el fichero.', max_length=200, verbose_name='Carpeta de Drive')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Último envío')),
                ('last_status', models.CharField(blank=True, choices=[('ok', 'Enviado'), ('failed', 'Falló')], max_length=10, verbose_name='Resultado')),
                ('last_error', models.TextField(blank=True, verbose_name='Último error')),
                ('user', models.ForeignKey(help_text='Dueño del envío: fija el ámbito del contenido y el destinatario por defecto.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'envío programado',
                'verbose_name_plural': 'envíos programados',
                'ordering': ['user__username', 'send_at', 'name'],
                'indexes': [models.Index(fields=['enabled', 'send_at'], name='idx_notif_enabled_time')],
            },
        ),
    ]
