# Generated by Django 5.2.16 on 2026-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_notificationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='outbox/%Y/%m/', verbose_name='Adjunto'),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del adjunto'),
        ),
    ]
