# Generated by Django 5.2.16 on 2026-08-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_emailoutbox_attachment_emailoutbox_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationschedule',
            name='filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Filtros'),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='name_with_date',
            field=models.BooleanField(default=False, verbose_name='Añadir la fecha al nombre'),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='name_with_time',
            field=models.BooleanField(default=False, verbose_name='Añadir la hora al nombre'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='content',
            field=models.CharField(choices=[('summary', 'Resumen de la flota'), ('fleet', 'Flota'), ('kmreadings', 'Kilometraje'), ('documents', 'Documentos'), ('alerts', 'Alertas'), ('invoices', 'Facturas'), ('costs', 'Costes'), ('users', 'Conductores')], max_length=12, verbose_name='Contenido'),
        ),
    ]
