# Generated by Django 5.2.16 on 2026-08-24 06:06

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_notification_csv_and_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_card',
            field=models.BooleanField(default=False, verbose_name='Tarjeta de combustible'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('itv_due', 'ITV próxima / vencida'), ('insurance_due', 'Seguro próximo / vencido'), ('km_reading_pending', 'Lectura de km pendiente'), ('km_overage', 'Exceso de km proyectado'), ('no_driver', 'Vehículo sin conductor'), ('maintenance_due', 'Mantenimiento programado')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('breakdown', 'Avería'), ('maintenance', 'Mantenimiento'), ('tires', 'Neumáticos'), ('inspection', 'ITV'), ('accident', 'Accidente')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, max_length=60, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiclelink',
            name='reason',
            field=models.CharField(choices=[('breakdown', 'Avería'), ('maintenance', 'Mantenimiento'), ('tires', 'Neumáticos'), ('inspection', 'ITV'), ('accident', 'Accidente')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('co2_factor', models.DecimalField(blank=True, decimal_places=4, help_text='Opcional: kg de CO₂ por litro (o kWh). Litros × factor = emisiones.', max_digits=8, null=True, verbose_name='Factor de emisión (kg CO₂/l o kWh)')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
            ],
            options={
                'verbose_name': 'tipo de combustible',
                'verbose_name_plural': 'tipos de combustible',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.fueltype', verbose_name='Combustible (catálogo)'),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('name', models.CharField(help_text='P. ej. «Revisión general» o «Neumáticos».', max_length=120, verbose_name='Nombre')),
                ('every_km', models.PositiveIntegerField(blank=True, help_text='Vacío = no aplica el ciclo por km.', null=True, verbose_name='Cada (km)')),
                ('every_months', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = no aplica el ciclo por tiempo.', null=True, verbose_name='Cada (meses)')),
                ('last_done_date', models.DateField(blank=True, null=True, verbose_name='Último realizado (fecha)')),
                ('last_done_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Último realizado (km)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='fleet.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['vehicle__plate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.site', verbose_name='Sede'),
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('period', models.DateField(help_text='Se normaliza al día 1 del mes.', verbose_name='Mes')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Si el extracto de la tarjeta lo trae.', max_digits=10, null=True, verbose_name='Importe (€)')),
                ('source', models.CharField(choices=[('fuel_card', 'Tarjeta de combustible'), ('manual', 'Manual'), ('import', 'Importación')], default='fuel_card', max_length=12, verbose_name='Origen')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='fleet.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'consumo de combustible',
                'verbose_name_plural': 'consumos de combustible',
                'ordering': ['-period', 'vehicle__plate'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle', 'period'), name='uniq_fuel_consumption_month')],
            },
        ),
        migrations.AddConstraint(
            model_name='fueltype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_fuel_type_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_site_name_ci'),
        ),
    ]
