# Generated by Django 5.2.16 on 2026-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_fuel_a_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationschedule',
            name='content',
            field=models.CharField(choices=[('summary', 'Resumen de la flota'), ('fleet', 'Flota'), ('kmreadings', 'Kilometraje'), ('fuel', 'Consumo de combustible'), ('documents', 'Documentos'), ('alerts', 'Alertas'), ('invoices', 'Facturas'), ('costs', 'Costes'), ('users', 'Conductores')], max_length=12, verbose_name='Contenido'),
        ),
    ]
