# Generated by Django 5.2.16 on 2026-08-25 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_incident_report_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Titular del documento personal (permiso de conducir…).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('registration_certificate', 'Permiso de circulación'), ('technical_datasheet', 'Ficha técnica'), ('insurance', 'Seguro'), ('contract', 'Contrato'), ('delivery_report', 'Acta de entrega'), ('return_report', 'Acta de devolución'), ('accident_report', 'Parte de accidente'), ('damage_photos', 'Fotos de daños'), ('driving_license', 'Permiso de conducir'), ('other', 'Otro')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='fleet_docum_user_id_3ec838_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', True), ('vehicle__isnull', False)), models.Q(('user__isnull', False), ('vehicle__isnull', True)), _connector='OR'), name='document_owner_vehicle_xor_user'),
        ),
    ]
