# Generated by Django 5.2.16 on 2026-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_document_user_alter_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolution_note',
            field=models.CharField(blank=True, help_text='Qué se hizo al resolverla (los cierres manuales desde la bandeja).', max_length=255, verbose_name='Nota de resolución'),
        ),
    ]
