# Generated by Django 5.2.16 on 2026-08-25 13:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_alert_resolution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitv',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que costó la inspección (opcional; se registra al resolver el aviso).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coste'),
        ),
    ]
