# Generated by Django 5.2.16 on 2026-08-26 04:37

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_eventitv_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('kind', models.CharField(choices=[('workshop', 'Taller'), ('itv', 'Estación ITV'), ('both', 'Taller + ITV')], default='workshop', max_length=20, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Código postal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
            ],
            options={
                'verbose_name': 'taller / estación ITV',
                'verbose_name_plural': 'talleres y estaciones ITV',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_workshop_name_ci')],
            },
        ),
    ]
