# Generated by Django 5.2.16 on 2026-08-26 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_incident_type_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('street', models.CharField(max_length=200, verbose_name='Calle')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Código postal')),
                ('locality', models.CharField(max_length=120, verbose_name='Localidad')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='Provincia')),
                ('occurred_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('police_report_ref', models.CharField(blank=True, max_length=120, verbose_name='Referencia del atestado')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accident_report', to='fleet.incident')),
            ],
            options={
                'verbose_name': 'parte de accidente',
                'verbose_name_plural': 'partes de accidente',
            },
        ),
        migrations.CreateModel(
            name='AccidentInjured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='Matrícula del vehículo')),
                ('seat', models.CharField(choices=[('driver', 'Conductor'), ('passenger', 'Pasajero')], default='driver', max_length=20, verbose_name='Posición')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injured', to='fleet.accidentreport')),
            ],
            options={
                'verbose_name': 'lesionado',
                'verbose_name_plural': 'lesionados',
            },
        ),
        migrations.CreateModel(
            name='AccidentThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='Matrícula')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('insurance_company', models.CharField(blank=True, max_length=150, verbose_name='Aseguradora')),
                ('policy_number', models.CharField(blank=True, max_length=100, verbose_name='Nº de póliza')),
                ('damage_description', models.TextField(blank=True, verbose_name='Daños')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_parties', to='fleet.accidentreport')),
            ],
            options={
                'verbose_name': 'tercero implicado',
                'verbose_name_plural': 'terceros implicados',
            },
        ),
    ]
