# Generated by Django 5.2.16 on 2026-08-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0042_accidentreport_accidentinjured_accidentthirdparty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceplan",
            name="name",
            field=models.CharField(
                help_text="P. ej. «Revisión general» o «Cambio de aceite».",
                max_length=120,
                verbose_name="Nombre",
            ),
        ),
    ]
