# Generated by Django 5.2.16 on 2026-09-03 17:51

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_alter_maintenanceplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Referencia del cliente')),
                ('response_status', models.PositiveSmallIntegerField(verbose_name='Código de la respuesta')),
                ('response_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Cuerpo de la respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'recibo de idempotencia',
                'verbose_name_plural': 'recibos de idempotencia',
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_idempotency_user_key')],
            },
        ),
    ]
