# Generated by Django 5.2.16 on 2026-09-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0044_idempotencyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviándose'), ('sent', 'Enviado'), ('failed', 'Fallido (sin más reintentos)')], default='pending', max_length=10, verbose_name='Estado'),
        ),
    ]
