# Generated by Django 5.2.16 on 2026-09-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0045_alter_emailoutbox_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date', '-pk'], 'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', '-pk'], 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'incidencia', 'verbose_name_plural': 'incidencias'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'factura', 'verbose_name_plural': 'facturas'},
        ),
        migrations.AlterModelOptions(
            name='kmreading',
            options={'ordering': ['-reading_date', '-pk'], 'verbose_name': 'lectura de km', 'verbose_name_plural': 'lecturas de km'},
        ),
        migrations.AlterModelOptions(
            name='vehiclelink',
            options={'ordering': ['-start_date', '-pk'], 'verbose_name': 'vínculo de sustitución', 'verbose_name_plural': 'vínculos de sustitución'},
        ),
        migrations.AlterModelOptions(
            name='vehicleusage',
            options={'ordering': ['-start_date', '-pk'], 'verbose_name': 'reparto de uso', 'verbose_name_plural': 'repartos de uso'},
        ),
    ]
