# Generated by Django 5.2.16 on 2026-09-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_alter_contract_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('creation', 'Alta'), ('activation', 'Activación'), ('deactivation', 'Desactivación'), ('invoice', 'Factura'), ('immobilization', 'Inmovilización'), ('reactivation', 'Reactivación'), ('insurance_renewal', 'Renovación de seguro'), ('penalty', 'Sanción'), ('location_change', 'Cambio de ubicación'), ('project_change', 'Cambio de proyecto'), ('breakdown', 'Avería'), ('km_reading', 'Lectura de km'), ('contract_change', 'Cambio de contrato'), ('fee_change', 'Cambio de cuota'), ('ceco_change', 'Cambio de CECO'), ('itv', 'ITV'), ('maintenance', 'Mantenimiento'), ('driver_change', 'Cambio de conductor'), ('supervisor_change', 'Cambio de supervisor')], max_length=30, verbose_name='Tipo de evento'),
        ),
        migrations.CreateModel(
            name='EventSupervisorChange',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supervisor_change', serialize=False, to='fleet.event')),
                ('new_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('old_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de supervisor',
                'verbose_name_plural': 'cambios de supervisor',
            },
        ),
    ]
