# Generated by Django 5.2.16 on 2026-09-08 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_resolution(apps, schema_editor):
    """Incidencias ya cerradas: la resolución vivía solo en `details["resolution"]`.

    Se copia a las columnas nuevas lo que ya se sabía: `resolution_date` y el
    coste (antes `overcost`, y solo si `cost` estaba vacío). Sin actor: nunca se
    registró quién cerró. Idempotente: solo rellena lo que está a NULL.
    """
    Incident = apps.get_model("fleet", "Incident")
    for incident in Incident.objects.filter(status="closed").iterator():
        resolution = (incident.details or {}).get("resolution") or {}
        if not isinstance(resolution, dict):
            continue
        changed = []
        if incident.resolution_date is None and resolution.get("resolution_date"):
            incident.resolution_date = resolution["resolution_date"]
            changed.append("resolution_date")
        if incident.cost is None and resolution.get("overcost") not in (None, ""):
            incident.cost = resolution["overcost"]
            changed.append("cost")
        if changed:
            incident.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0047_alter_event_event_type_eventsupervisorchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de solución'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km en la solución'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por'),
        ),
        migrations.AddField(
            model_name='incident',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='fleet.workshop', verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('registration_certificate', 'Permiso de circulación'), ('technical_datasheet', 'Ficha técnica'), ('insurance', 'Seguro'), ('contract', 'Contrato'), ('delivery_report', 'Acta de entrega'), ('return_report', 'Acta de devolución'), ('accident_report', 'Parte de accidente'), ('damage_photos', 'Fotos de daños'), ('itv_report', 'Informe de ITV'), ('workshop_invoice', 'Factura de taller'), ('driving_license', 'Permiso de conducir'), ('other', 'Otro')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coste de la reparación/servicio; lo fija la resolución.', max_digits=10, null=True, verbose_name='Coste'),
        ),
        migrations.RunPython(backfill_resolution, migrations.RunPython.noop),
    ]
