# Generated by Django 5.2.16 on 2026-09-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0048_incident_resolution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitv',
            name='km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km en la inspección'),
        ),
        migrations.AddField(
            model_name='eventitv',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itv_events', to='fleet.workshop', verbose_name='Estación ITV'),
        ),
    ]
