# Generated by Django 5.2.16 on 2026-09-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0049_eventitv_workshop_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInsuranceRenewal',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='insurance_renewal', serialize=False, to='fleet.event')),
                ('old_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento anterior')),
                ('new_expiry', models.DateField(verbose_name='Vencimiento nuevo')),
            ],
            options={
                'verbose_name': 'renovación de seguro',
                'verbose_name_plural': 'renovaciones de seguro',
            },
        ),
    ]
