# Generated by Django 5.2.16 on 2026-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0050_eventinsurancerenewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('itv_due', 'ITV programada'), ('insurance_due', 'Seguro próximo / vencido'), ('km_reading_pending', 'Lectura de km pendiente'), ('km_overage', 'Exceso de km proyectado'), ('no_driver', 'Vehículo sin conductor'), ('maintenance_due', 'Mantenimiento programado')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('breakdown', 'Avería'), ('maintenance', 'Mantenimiento puntual'), ('tires', 'Avería de neumáticos'), ('inspection', 'ITV'), ('accident', 'Accidente'), ('general', 'Petición general')], max_length=20, verbose_name='Tipo'),
        ),
    ]
