# Generated by Django 5.2.16 on 2026-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0051_alter_alert_type_alter_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('critical', 'Crítica'), ('moderate', 'Moderada'), ('functional', 'Funcional'), ('informative', 'Informativa')], default='moderate', max_length=20, verbose_name='Prioridad'),
        ),
    ]
