# Generated by Django 5.2.16 on 2026-09-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0052_incident_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='workshop_postal_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='CP preferente'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='itv_postal_code',
            field=models.CharField(blank=True, help_text='Ubicación de referencia para que un tercero busque la estación de ITV más cercana; se pide al programar la cita.', max_length=12, verbose_name='CP preferente para la ITV'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_itv_manual',
            field=models.BooleanField(default=False, help_text='La cita la programó la gestión y no sale de un `EventItv`: el job `refresh_next_itv` no la toca. Registrar una ITV real la desmarca.', verbose_name='Próxima ITV programada a mano'),
        ),
    ]
