# Generated by Django 5.2.16 on 2026-09-10 11:27

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0053_maintenanceplan_workshop_postal_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('name', models.CharField(help_text='P. ej. «Revisión general» o «Cambio de aceite».', max_length=120, verbose_name='Nombre')),
                ('every_km', models.PositiveIntegerField(blank=True, help_text='Vacío = no aplica el ciclo por km.', null=True, verbose_name='Cada (km)')),
                ('every_months', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = no aplica el ciclo por tiempo.', null=True, verbose_name='Cada (meses)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
            ],
            options={
                'verbose_name': 'programa de mantenimiento',
                'verbose_name_plural': 'programas de mantenimiento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='fleet.maintenanceprogram', verbose_name='Programa'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_maintenance_program_name_ci'),
        ),
    ]
