# Generated by Django 5.2.16 on 2026-09-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0054_maintenanceprogram_maintenanceplan_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('maintenance', 'No activo - Mantenimiento'), ('itv', 'No activo - ITV'), ('broken', 'No activo - Averiado'), ('accidente', 'No activo - Accidentado'), ('non_active', 'No activo'), ('retired', 'Devuelto (baja)')], max_length=20, verbose_name='Estado'),
        ),
    ]
