# Generated by Django 5.2.16 on 2026-09-11 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0055_alter_vehicle_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el')),
                ('deactivation_reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, help_text='NULL = en curso.', null=True, verbose_name='Fin')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_periods', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_periods', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'periodo de supervisión',
                'verbose_name_plural': 'periodos de supervisión',
                'ordering': ['-start_date', '-pk'],
                'indexes': [models.Index(fields=['vehicle', 'end_date'], name='fleet_super_vehicle_4fa317_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_active', True)), fields=('vehicle',), name='unique_open_supervisor_period_per_vehicle')],
            },
        ),
    ]
