# Generated by Django 5.2.16 on 2026-09-14 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0057_periodos_supervisor_desde_eventos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'alerta', 'verbose_name_plural': 'alertas'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'asignación', 'verbose_name_plural': 'asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'envío de correo', 'verbose_name_plural': 'envíos de correo'},
        ),
        migrations.AlterModelOptions(
            name='invoiceallocation',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'imputación de factura', 'verbose_name_plural': 'imputaciones de factura'},
        ),
        migrations.AlterModelOptions(
            name='vehiclerequest',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'solicitud de vehículo', 'verbose_name_plural': 'solicitudes de vehículo'},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alert_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['vehicle', 'status'], name='incident_vehicle_status_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['vehicle', 'type', 'status'], name='incident_veh_type_status_idx'),
        ),
    ]
