# Generated by Django 5.2.16 on 2026-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0058_r5_incident_indexes_and_orderings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_missing_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que la comprobación de existencia no encontró el archivo donde se archivó (Drive o disco). Vacío si existe o si no se ha podido comprobar. Un documento así se puede borrar definitivamente desde la propia lista.', null=True, verbose_name='Archivo no encontrado desde'),
        ),
    ]
