# Generated by Django 5.2.16 on 2026-09-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0062_document_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_requests', to='fleet.incident', verbose_name='Incidencia de origen'),
        ),
    ]
