# Generated by Django 5.2.16 on 2026-09-18 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def compartir_lo_existente(apps, schema_editor):
    """Lo ya subido se queda como estaba: lo leen todos los conductores.

    El interruptor nace APAGADO, así que sin este paso los documentos
    anteriores —sin responsable, sin compartir— desaparecerían de golpe para
    todo el que no sea gestión. La regla nueva restringe lo que se suba a
    partir de ahora, no borra de la vista el histórico.
    """
    apps.get_model("fleet", "Document").objects.update(shared_read=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0063_vehiclerequest_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='protected',
            field=models.BooleanField(default=False, help_text='No lo ve ningún conductor ni supervisor, solo la gestión. Única excepción: el titular de un documento personal sigue viendo el suyo (derecho de acceso, RGPD).', verbose_name='Protegido'),
        ),
        migrations.AddField(
            model_name='document',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='De quién es el documento. Lo rellena el alta: el titular si es personal, y el conductor vigente si es de un vehículo. Es una FOTO FIJA: al rotar el conductor, el documento no cambia de responsable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_responsible_for', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='document',
            name='shared_read',
            field=models.BooleanField(default=False, help_text='Lo leen TODOS los conductores del vehículo. Sin marcar, solo su responsable.', verbose_name='Lectura compartida'),
        ),
        # Hacia atrás no hay nada que deshacer: los campos se van con el resto.
        migrations.RunPython(compartir_lo_existente, migrations.RunPython.noop),
    ]
