# Generated by Django 5.2.16 on 2026-09-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0064_document_protected_document_responsible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('reason', models.TextField(blank=True, help_text='Por qué pide borrarlo quien lo ve (está repetido, es de otro coche…).', verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('deleted', 'Borrado (en erratas)'), ('hidden', 'Oculto para el conductor'), ('rejected', 'Rechazada')], default='pending', max_length=15, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Observaciones de la resolución')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='fleet.document', verbose_name='Documento')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'petición de borrado de documento',
                'verbose_name_plural': 'peticiones de borrado de documento',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('document',), name='unique_pending_document_deletion')],
            },
        ),
    ]
