# Generated by Django 5.2.16 on 2026-09-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0066_vehicle_state_non_active_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('proposed_name', models.CharField(blank=True, help_text='A quién se propone cuando no es un usuario de la aplicación.', max_length=150, verbose_name='Nombre propuesto')),
                ('proposed_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo propuesto')),
                ('note', models.TextField(blank=True, help_text='Lo que quien propone le cuenta a administración.', verbose_name='Nota')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Atendida'), ('rejected', 'Rechazada')], default='pending', max_length=15, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Observaciones de la resolución')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_change_requests', to='fleet.alert', verbose_name='Alerta de origen')),
                ('proposed_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Conductor propuesto')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_change_requests', to='fleet.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'propuesta de cambio de conductor',
                'verbose_name_plural': 'propuestas de cambio de conductor',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('vehicle',), name='unique_pending_driver_change')],
            },
        ),
    ]
