# Generated by Django 5.2.16 on 2026-09-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0067_driverchangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Solo lo que cambia: {campo: valor propuesto}.', verbose_name='Cambios propuestos')),
                ('note', models.TextField(blank=True, help_text='Lo que quien la abre le cuenta a administración.', verbose_name='Nota')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Aplicada'), ('rejected', 'Rechazada')], default='pending', max_length=15, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Observaciones de la resolución')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'petición de corrección de ficha',
                'verbose_name_plural': 'peticiones de corrección de ficha',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_profile_change')],
            },
        ),
    ]
