# Generated by Django 5.2.16 on 2026-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0068_profilechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdeletionrequest',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cambios propuestos'),
        ),
        migrations.AddField(
            model_name='documentdeletionrequest',
            name='kind',
            field=models.CharField(choices=[('delete', 'Borrado'), ('change', 'Corrección')], default='delete', max_length=10, verbose_name='Qué se pide'),
        ),
        migrations.AlterField(
            model_name='documentdeletionrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Por qué lo pide quien lo ve (está repetido, es de otro coche, la fecha está mal…).', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='documentdeletionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('deleted', 'Borrado (en erratas)'), ('hidden', 'Oculto para el conductor'), ('applied', 'Corrección aplicada'), ('rejected', 'Rechazada')], default='pending', max_length=15, verbose_name='Estado'),
        ),
    ]
