# Generated by Django 5.2.16 on 2026-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0069_documentdeletionrequest_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message_args',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos del mensaje'),
        ),
        migrations.AddField(
            model_name='alert',
            name='message_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Código del mensaje'),
        ),
    ]
