# Generated by Django 5.2.16 on 2026-09-22 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0070_alert_message_args_alert_message_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_plate', message='Matrícula no válida: solo mayúsculas, dígitos, guion o espacio interior (de 3 a 15 caracteres).', regex='^[A-Z0-9][A-Z0-9 -]{1,13}[A-Z0-9]$')], verbose_name='Matrícula'),
        ),
    ]
