# Generated by Django 5.2.16 on 2026-09-23 09:19

from django.db import migrations, models

# Solo la ETIQUETA del campo: el consumo medio se mide en l/100km (o kWh/100km),
# que es lo que marca un ordenador de a bordo y lo que ya decía
# `Vehicle.consumption`. Las cifras guardadas no cambian -- siempre fueron eso.


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0071_vehicle_plate_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='avg_consumption',
            field=models.DecimalField(decimal_places=2, help_text='El del último trayecto o ciclo de repostaje que marca el ordenador de a bordo, no el histórico acumulado del vehículo.', max_digits=8, verbose_name='Consumo medio real (l/100km o kWh/100km)'),
        ),
    ]
